//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Training.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRRTEntities : DbContext
    {
        public HRRTEntities()
            : base("name=HRRTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Bill> tbl_Bill { get; set; }
        public virtual DbSet<tbl_Company> tbl_Company { get; set; }
        public virtual DbSet<tbl_CompanyAndCourse> tbl_CompanyAndCourse { get; set; }
        public virtual DbSet<tbl_Course> tbl_Course { get; set; }
        public virtual DbSet<tbl_CourseLog> tbl_CourseLog { get; set; }
        public virtual DbSet<tbl_CourseTopicLog> tbl_CourseTopicLog { get; set; }
        public virtual DbSet<tbl_CourseTopicStory> tbl_CourseTopicStory { get; set; }
        public virtual DbSet<tbl_Department> tbl_Department { get; set; }
        public virtual DbSet<tbl_Employee> tbl_Employee { get; set; }
        public virtual DbSet<tbl_EmployeeCourse> tbl_EmployeeCourse { get; set; }
        public virtual DbSet<tbl_LoginHistory> tbl_LoginHistory { get; set; }
        public virtual DbSet<tbl_Question> tbl_Question { get; set; }
        public virtual DbSet<tbl_Story> tbl_Story { get; set; }
        public virtual DbSet<tbl_Title> tbl_Title { get; set; }
        public virtual DbSet<tbl_Topic> tbl_Topic { get; set; }
        public virtual DbSet<tbl_TrainingProgress> tbl_TrainingProgress { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
        public virtual DbSet<tbl_UserEmployee> tbl_UserEmployee { get; set; }
        public virtual DbSet<tbl_UserRole> tbl_UserRole { get; set; }
        public virtual DbSet<tbl_ProgressTransaction> tbl_ProgressTransaction { get; set; }
    }
}
