//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Training.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmployeeCourse
    {
        public int EmployeeCourseID { get; set; }
        public int CourseID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime DueDateTime { get; set; }
        public Nullable<decimal> Progress { get; set; }
    
        public virtual tbl_Course tbl_Course { get; set; }
        public virtual tbl_Employee tbl_Employee { get; set; }
    }
}
