//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Training.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LoginHistory
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public string IPAddress { get; set; }
        public bool LoginStatus { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime LastModifiedOn { get; set; }
    }
}
