//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Training.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Bill()
        {
            this.tbl_CompanyAndCourse = new HashSet<tbl_CompanyAndCourse>();
        }
    
        public int Id { get; set; }
        public string BillNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public string Description { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public decimal BillAmount { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime LastModifiedOn { get; set; }
    
        public virtual tbl_Company tbl_Company { get; set; }
        public virtual tbl_User tbl_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CompanyAndCourse> tbl_CompanyAndCourse { get; set; }
    }
}
