//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Training.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProgressTransaction
    {
        public int Id { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> TopicID { get; set; }
        public Nullable<int> StoryID { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<int> Score { get; set; }
        public bool AnswerStatus { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime LastModifiedOn { get; set; }
    
        public virtual tbl_Course tbl_Course { get; set; }
        public virtual tbl_Employee tbl_Employee { get; set; }
        public virtual tbl_Question tbl_Question { get; set; }
        public virtual tbl_Story tbl_Story { get; set; }
        public virtual tbl_Topic tbl_Topic { get; set; }
    }
}
