//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Training.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Question()
        {
            this.tbl_ProgressTransaction = new HashSet<tbl_ProgressTransaction>();
        }
    
        public int ID { get; set; }
        public Nullable<int> StoryId { get; set; }
        public string Questoin { get; set; }
        public string Answer { get; set; }
        public Nullable<bool> IsCorrect { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime LastModifiedOn { get; set; }
    
        public virtual tbl_Story tbl_Story { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ProgressTransaction> tbl_ProgressTransaction { get; set; }
    }
}
