//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Training.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TrainingProgress
    {
        public int Id { get; set; }
        public int EmployeeID { get; set; }
        public int CourseID { get; set; }
        public bool Status { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public string Answer { get; set; }
        public int Score { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime LastModifiedOn { get; set; }
    
        public virtual tbl_Course tbl_Course { get; set; }
        public virtual tbl_Employee tbl_Employee { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
